CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE users (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name text NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 100),
 role text NOT NULL CHECK (role IN ('TECHNICIAN','MANAGER')),
 created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE TABLE assets (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 asset_code text NOT NULL UNIQUE CHECK (length(trim(asset_code)) BETWEEN 1 AND 80),
 asset_type text NOT NULL CHECK (length(trim(asset_type)) BETWEEN 1 AND 80),
 model_name text NOT NULL,
 status text NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','RETIRED')),
 acquired_at date,
 created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE TABLE asset_slots (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 asset_id bigint NOT NULL REFERENCES assets(id) ON DELETE RESTRICT,
 slot_name text NOT NULL CHECK (length(trim(slot_name)) BETWEEN 1 AND 80),
 allowed_type text NOT NULL CHECK (length(trim(allowed_type)) BETWEEN 1 AND 80),
 created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 UNIQUE(asset_id,slot_name)
);
CREATE TABLE component_models (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 component_type text NOT NULL CHECK (length(trim(component_type)) BETWEEN 1 AND 80),
 manufacturer text NOT NULL,
 model_name text NOT NULL CHECK (length(trim(model_name)) BETWEEN 1 AND 100),
 description text NOT NULL DEFAULT ''
);
CREATE TABLE component_batches (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 component_model_id bigint NOT NULL REFERENCES component_models(id) ON DELETE RESTRICT,
 batch_code text NOT NULL UNIQUE CHECK (length(trim(batch_code)) BETWEEN 1 AND 80),
 manufactured_at date,
 recall_status text NOT NULL DEFAULT 'NORMAL' CHECK (recall_status IN ('NORMAL','RECALLED')),
 recalled_at timestamptz,
 recalled_by bigint REFERENCES users(id) ON DELETE RESTRICT,
 recall_reason text,
 CHECK ((recall_status='NORMAL' AND recalled_at IS NULL AND recall_reason IS NULL AND recalled_by IS NULL)
 OR (recall_status='RECALLED' AND recalled_at IS NOT NULL AND length(trim(recall_reason)) > 0
 AND recall_reason IS NOT NULL AND recalled_by IS NOT NULL))
);
CREATE TABLE components (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 serial_no text NOT NULL UNIQUE CHECK (length(trim(serial_no)) BETWEEN 1 AND 80),
 batch_id bigint NOT NULL REFERENCES component_batches(id) ON DELETE RESTRICT,
 condition_status text NOT NULL DEFAULT 'GOOD' CHECK (condition_status IN ('GOOD','DEFECTIVE','RETIRED')),
 created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE TABLE maintenance_events (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 asset_id bigint NOT NULL REFERENCES assets(id) ON DELETE RESTRICT,
 technician_id bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
 event_type text NOT NULL CHECK (event_type IN ('INSTALL','REMOVE','SWAP')),
 occurred_at timestamptz NOT NULL,
 note text NOT NULL DEFAULT ''
);
CREATE TABLE installations (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 asset_slot_id bigint NOT NULL REFERENCES asset_slots(id) ON DELETE RESTRICT,
 component_id bigint NOT NULL REFERENCES components(id) ON DELETE RESTRICT,
 installed_at timestamptz NOT NULL,
 removed_at timestamptz,
 installed_event_id bigint NOT NULL REFERENCES maintenance_events(id) ON DELETE RESTRICT,
 removed_event_id bigint REFERENCES maintenance_events(id) ON DELETE RESTRICT,
 CHECK (removed_at IS NULL OR removed_at > installed_at),
 CHECK ((removed_at IS NULL) = (removed_event_id IS NULL)),
 EXCLUDE USING gist (component_id WITH =, tstzrange(installed_at,removed_at,'[)') WITH &&),
 EXCLUDE USING gist (asset_slot_id WITH =, tstzrange(installed_at,removed_at,'[)') WITH &&)
);
CREATE UNIQUE INDEX ux_component_active ON installations(component_id) WHERE removed_at IS NULL;
CREATE UNIQUE INDEX ux_slot_active ON installations(asset_slot_id) WHERE removed_at IS NULL;
CREATE INDEX ix_slots_asset ON asset_slots(asset_id);
CREATE INDEX ix_components_batch ON components(batch_id);
CREATE INDEX ix_batches_model ON component_batches(component_model_id);
CREATE INDEX ix_events_asset_time ON maintenance_events(asset_id,occurred_at DESC);
CREATE INDEX ix_installations_slot_time ON installations(asset_slot_id,installed_at);
CREATE INDEX ix_installations_component_time ON installations(component_id,installed_at);

-- History may only be closed once. Identity, provenance and past events are immutable.
CREATE FUNCTION guard_installation_history() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'Installation history cannot be deleted' USING ERRCODE='23514'; END IF;
 IF OLD.removed_at IS NOT NULL OR
 ROW(NEW.id,NEW.asset_slot_id,NEW.component_id,NEW.installed_at,NEW.installed_event_id)
 IS DISTINCT FROM ROW(OLD.id,OLD.asset_slot_id,OLD.component_id,OLD.installed_at,OLD.installed_event_id)
 OR NEW.removed_at IS NULL THEN
 RAISE EXCEPTION 'Installation history is immutable' USING ERRCODE='23514'; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER preserve_installation BEFORE UPDATE OR DELETE ON installations
 FOR EACH ROW EXECUTE FUNCTION guard_installation_history();

CREATE OR REPLACE FUNCTION guard_reference_history() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 CASE TG_TABLE_NAME
 WHEN 'maintenance_events' THEN
   RAISE EXCEPTION 'Maintenance events are immutable' USING ERRCODE='23514';
 WHEN 'components' THEN
   IF ROW(NEW.serial_no,NEW.batch_id,NEW.created_at) IS DISTINCT FROM ROW(OLD.serial_no,OLD.batch_id,OLD.created_at) THEN
     RAISE EXCEPTION 'Component identity and provenance are immutable' USING ERRCODE='23514';
   END IF;
 WHEN 'asset_slots' THEN
   RAISE EXCEPTION 'Slots are immutable' USING ERRCODE='23514';
 WHEN 'assets' THEN
   IF ROW(NEW.asset_code,NEW.created_at) IS DISTINCT FROM ROW(OLD.asset_code,OLD.created_at) THEN
     RAISE EXCEPTION 'Asset identity is immutable' USING ERRCODE='23514';
   END IF;
 WHEN 'component_batches' THEN
   IF ROW(NEW.batch_code,NEW.component_model_id,NEW.manufactured_at)
     IS DISTINCT FROM ROW(OLD.batch_code,OLD.component_model_id,OLD.manufactured_at) OR OLD.recall_status='RECALLED' THEN
     RAISE EXCEPTION 'Batch provenance and recall are immutable' USING ERRCODE='23514';
   END IF;
 WHEN 'component_models' THEN
   RAISE EXCEPTION 'Component models are immutable' USING ERRCODE='23514';
 ELSE NULL;
 END CASE;
 RETURN NEW;
END $$;
CREATE TRIGGER preserve_event BEFORE UPDATE OR DELETE ON maintenance_events
 FOR EACH ROW EXECUTE FUNCTION guard_reference_history();
CREATE TRIGGER preserve_component BEFORE UPDATE ON components
 FOR EACH ROW EXECUTE FUNCTION guard_reference_history();
CREATE TRIGGER preserve_slot BEFORE UPDATE ON asset_slots
 FOR EACH ROW EXECUTE FUNCTION guard_reference_history();
CREATE TRIGGER preserve_asset BEFORE UPDATE ON assets
 FOR EACH ROW EXECUTE FUNCTION guard_reference_history();
CREATE TRIGGER preserve_batch BEFORE UPDATE ON component_batches
 FOR EACH ROW EXECUTE FUNCTION guard_reference_history();
CREATE TRIGGER preserve_model BEFORE UPDATE ON component_models
 FOR EACH ROW EXECUTE FUNCTION guard_reference_history();
